import {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,Header,Footer,PageNumber,BorderStyle,ShadingType,VerticalAlign,PageOrientation,ImageRun,SectionType} from 'npm:docx@9.5.1';
import {TEAL,BLACK,GRAY,LIGHT,clean,pct,fmt,flabel,teacher,qValue,instructions,bpRows,normalizeOptions} from './helpers.ts';
import {headerBytes} from './asset.ts';
const run=(t:any,b=false,s=22,c=BLACK)=>new TextRun({text:clean(t),bold:b,font:'Arial',size:s,color:c});
const p=(t:any,o:any={})=>new Paragraph({alignment:o.align||AlignmentType.JUSTIFIED,spacing:{after:o.after??55,before:o.before??0,line:o.line??220},children:[run(t,!!o.bold,o.size??22,o.color||BLACK)]});
const center=(t:any,b=true,s=24,c=BLACK)=>p(t,{align:AlignmentType.CENTER,bold:b,size:s,color:c,after:55});
const imagePara=()=>new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:80},children:[new ImageRun({data:headerBytes(),transformation:{width:640,height:78},type:'png'})]});
const cell=(t:any,h=false,s=17)=>new TableCell({verticalAlign:VerticalAlign.CENTER,shading:h?{type:ShadingType.CLEAR,fill:LIGHT}:undefined,margins:{top:55,bottom:55,left:70,right:70},children:[p(t,{size:s,bold:h,align:AlignmentType.LEFT,after:0})]});
const tbl=(rows:string[][],fs=17)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:rows.map((r,i)=>new TableRow({cantSplit:true,children:r.map(x=>cell(x,i===0,fs))}))});
const ident=(a:any,c:any,cl:any)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[new TableCell({columnSpan:2,children:[center(`AVALIAÇÃO ${a.assessment_type} 2026.2`,true,22)]})]}),new TableRow({children:[cell(`Disciplina: ${c.name}`),cell('Data: ____/____/2026')]}),new TableRow({children:[cell('Aluno(a): _________________________________________________'),cell(`Turma: ${cl?.name||'________'}`)]}),new TableRow({children:[cell(`Docentes: ${teacher(c.code||c.name)}`),cell('Nota: ______')]})]});
const anti=()=>new Table({width:{size:94,type:WidthType.PERCENTAGE},alignment:AlignmentType.CENTER,borders:{top:{style:BorderStyle.SINGLE,size:10,color:BLACK},bottom:{style:BorderStyle.SINGLE,size:10,color:BLACK},left:{style:BorderStyle.SINGLE,size:10,color:BLACK},right:{style:BorderStyle.SINGLE,size:10,color:BLACK},insideHorizontal:{style:BorderStyle.NONE},insideVertical:{style:BorderStyle.NONE}},rows:[new TableRow({children:[new TableCell({margins:{top:80,bottom:80,left:120,right:120},children:[center('LEIA ESSE INSTRUTIVO ANTES DE INICIAR A RESOLUÇÃO DA SUA AVALIAÇÃO.',true,17),p('Fica terminantemente proibido aos alunos:',{size:16,align:AlignmentType.LEFT,after:20}),...['Comunicação irregular entre alunos durante a prova;','Consultas a manuscrito, material impresso ou recursos eletrônicos;','Utilização de equipamento eletrônico de qualquer natureza;','Escrita em carteira, paredes, mãos ou outras partes do corpo;'].map(x=>p('- '+x,{size:16,align:AlignmentType.LEFT,after:18})),p('COLAS/PESCAS implicam retenção da avaliação e encaminhamento à coordenação.',{size:16,bold:true,align:AlignmentType.LEFT})]})]})]});
const gab=(n:number)=>tbl([['Q','1','2','3','4','5','6','7','8','9','10'],['R',...Array.from({length:10},(_,i)=>i<n?'(   )':'')]],16);
function qblock(it:any){const f=fmt(it),out:any[]=[p(`QUESTÃO ${String(it.item_number).padStart(2,'0')}  (${flabel(f)})`,{bold:true,size:18,align:AlignmentType.LEFT,after:25}),p(it.stem,{size:18,line:210,after:30})];if(f==='VERDADEIRO_FALSO')(it.format_payload?.statements||[]).forEach((x:any,i:number)=>out.push(p(`${['I','II','III','IV'][i]}. ${clean(x?.text??x)}`,{size:17,align:AlignmentType.LEFT,after:18})));if(f==='ASSOCIACAO_COLUNAS'){const A=it.format_payload?.column_i||[],B=it.format_payload?.column_ii||[];out.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cell('COLUNA I',true,15),cell('COLUNA II',true,15)]}),...Array.from({length:4},(_,i)=>new TableRow({children:[cell(`${i+1}. ${A[i]||''}`,false,15),cell(`( ) ${B[i]||''}`,false,15)]}))]}))}if(f!=='DISCURSIVA')normalizeOptions(it).forEach((o,i)=>out.push(p(`${String.fromCharCode(65+i)}) ${o.replace(/^[A-E]\)\s*/,'')}`,{size:17,align:AlignmentType.LEFT,after:18})));return out}
function objectivePages(items:any[]){const obj=items.filter(x=>fmt(x)!=='DISCURSIVA');const pages:any[]=[];for(let start=0;start<obj.length;start+=4){const group=obj.slice(start,start+4),L:any[]=[],R:any[]=[];group.forEach((it,i)=>(i<2?L:R).push(...qblock(it),p('',{after:20})));pages.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE},insideHorizontal:{style:BorderStyle.NONE},insideVertical:{style:BorderStyle.SINGLE,size:1,color:'B7B7B7'}},rows:[new TableRow({cantSplit:false,children:[new TableCell({width:{size:50,type:WidthType.PERCENTAGE},margins:{left:60,right:110},children:L}),new TableCell({width:{size:50,type:WidthType.PERCENTAGE},margins:{left:110,right:60},children:R})]})]}));}return pages}
const hdr=()=>new Header({children:[imagePara()]});const ftr=()=>new Footer({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[run('Estácio–IDOMED – Iguatu   |   Página ',false,13,GRAY),new TextRun({children:[PageNumber.CURRENT],font:'Arial',size:13,color:GRAY})]})]});
export async function makeDocx(type:string,a:any,items:any[],c:any,cl:any){let sections:any[]=[];if(type==='EXAM_TEMPLATE'){const first=[imagePara(),ident(a,c,cl),p(''),anti(),center('GABARITO DO ALUNO',true,20),gab(Number(a.objective_count||0)),center('INSTRUÇÕES',true,18),...instructions(a).map(x=>p('- '+x,{size:16,align:AlignmentType.LEFT,after:20}))];sections.push({properties:{page:{margin:{top:380,right:420,bottom:420,left:420}}},footers:{default:ftr()},children:first});for(const page of objectivePages(items))sections.push({properties:{type:SectionType.NEXT_PAGE,page:{margin:{top:330,right:380,bottom:380,left:380}}},headers:{default:hdr()},footers:{default:ftr()},children:[page]});for(const it of items.filter(x=>fmt(x)==='DISCURSIVA')){const ch:any[]=[...qblock(it)];for(let k=0;k<8;k++)ch.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:1,color:'AFAFAF'}},spacing:{after:130},children:[run('')]}));sections.push({properties:{type:SectionType.NEXT_PAGE,page:{margin:{top:380,right:440,bottom:440,left:440}}},headers:{default:hdr()},footers:{default:ftr()},children:ch})}}else{let ch:any[]=[imagePara()];const rows=bpRows(a,items);if(type==='BLUEPRINT_REPORT')ch.push(center('RELATÓRIO DO BLUEPRINT',true,25),center(`${c.name} | ${a.assessment_type} | ${cl?.name||''}`,false,17,GRAY),p('Matriz de especificações vinculante da Skill Oficial MEDICINA-V7.1-CONFORMIDADE-2026.',{size:17}),tbl([['Item','Formato','Conteúdo','Objetivo / Competência','Bloom','Dific.','Angoff','Palavras','Peso'],...rows],14));if(type==='COMMENTED_KEY'){ch.push(center('GABARITO COMENTADO',true,25));for(const it of items){ch.push(p(`Questão ${it.item_number} - ${flabel(fmt(it))}${fmt(it)!=='DISCURSIVA'?` - Gabarito: ${it.correct_answer}`:''}`,{bold:true,size:18,color:TEAL,align:AlignmentType.LEFT}),p(it.rationale||it.justification,{size:17}));if(fmt(it)==='DISCURSIVA')ch.push(p('Rubrica analítica',{bold:true,size:17,align:AlignmentType.LEFT}),p(it.rubric,{size:17}))}}if(type==='TECHNICAL_DOSSIER')ch.push(center('CADERNO TÉCNICO DO PROFESSOR',true,25),p('Avaliação construída segundo a Skill Oficial MEDICINA-V7.1-CONFORMIDADE-2026, com blueprint prévio, formatos vinculantes, Angoff e auditoria bloqueante.',{size:17}),tbl([['Item','Formato','Conteúdo','Objetivo / Competência','Bloom','Dific.','Angoff','Palavras','Peso'],...rows],14),p('Resultado: APROVADO PARA APLICAÇÃO DOCENTE após auditoria V7.1.',{bold:true,size:18}));sections=[{properties:{page:{size:{orientation:type==='BLUEPRINT_REPORT'?PageOrientation.LANDSCAPE:PageOrientation.PORTRAIT},margin:{top:420,right:420,bottom:420,left:420}}},footers:{default:ftr()},children:ch}]}return await Packer.toBuffer(new Document({creator:'IDOMED-CANONICAL-EXAM-V2',description:'Template institucional canônico bloqueado',styles:{default:{document:{run:{font:'Arial',size:22,color:BLACK},paragraph:{spacing:{line:220}}}}},sections}))}
