export const TEAL='006B63',BLACK='111111',GRAY='666666',LIGHT='EAF5F3';
export const clean=(s:any)=>String(s??'').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/\s+/g,' ').trim();
export const safe=(s:any)=>clean(s).replace(/−/g,'-').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/≠/g,'!=').replace(/→/g,'->').replace(/×/g,'x').replace(/○/g,'( )').replace(/•/g,'-').replace(/✓/g,'V').replace(/µ/g,'u').replace(/³/g,'3').replace(/[^\u0009\u000A\u000D\u0020-\u007E\u00A0-\u00FF]/g,'?');
export const fmt=(x:any)=>String(x.item_format||(x.item_type==='Discursiva'?'DISCURSIVA':'RESPOSTA_UNICA'));
export const flabel=(f:string)=>f==='RESPOSTA_UNICA'?'Resposta única':f==='VERDADEIRO_FALSO'?'V/F':f==='ASSOCIACAO_COLUNAS'?'Associação':'Discursiva';
export const pct=(n:any)=>Number(n||0).toFixed(Number(n||0)%1?1:0).replace('.',',');
export const words=(s:any)=>clean(s).split(/\s+/).filter(Boolean).length;
export function teacher(code:string){return /PASI|PAS1|PAS I/i.test(code)?'Prof. Raimundo Tavares de Luna Neto | Prof. José Evaldo Gomes Júnior':'Prof. Raimundo Tavares de Luna Neto'}
export function qValue(a:any,it:any){const rows=a.blueprint?.rows||a.blueprint?.items||[];const r=rows.find((x:any)=>Number(x.item??x.number)===Number(it.item_number));const w=Number(r?.weight_percent||String(r?.weight||'').replace('%','').replace(',','.'));const total=Number(a.total_points||0),n=Number(a.objective_count||0)+Number(a.discursive_count||0);return w?total*w/100:total/Math.max(1,n)}
export function angoff(a:any,it:any){const rows=a.blueprint?.rows||a.blueprint?.items||[];const r=rows.find((x:any)=>Number(x.item??x.number)===Number(it.item_number))||{};const v=r.angoff_modified??r.angoff??r.cut_score??it.angoff_modified??it.angoff;return v==null?'A definir':String(v).replace('.',',')}
export function instructions(a:any){return ['Leia cada situação-problema com atenção.','Nas questões objetivas, marque apenas uma alternativa no gabarito.','Nas questões de Verdadeiro/Falso e Associação, assinale a alternativa que representa a sequência correta.','Nas questões discursivas, registre raciocínio, cálculos quando solicitados e interpretação final.',`A prova contém ${a.objective_count} questões objetivas e ${a.discursive_count} discursivas, totalizando ${pct(a.total_points)} pontos.`]}
export function normalizeOptions(it:any):string[]{return (Array.isArray(it.options)?it.options:[]).map((o:any)=>{if(typeof o==='string')return clean(o);if(o&&typeof o==='object')return clean(o.text??o.label??o.value??o.option??'');return clean(o)}).filter(Boolean)}
export function validateContent(items:any[]){const errors:string[]=[];for(const it of items){const f=fmt(it),opts=normalizeOptions(it);if(!it.stem||words(it.stem)<70)errors.push(`Q${it.item_number}: enunciado insuficiente`);if(f!=='DISCURSIVA'&&opts.length!==5)errors.push(`Q${it.item_number}: deve possuir 5 alternativas`);if(f==='RESPOSTA_UNICA'&&opts.some(x=>x==='[object Object]'||!x))errors.push(`Q${it.item_number}: alternativas corrompidas`);if(f==='VERDADEIRO_FALSO'&&(it.format_payload?.statements||[]).length!==4)errors.push(`Q${it.item_number}: V/F sem 4 sentenças`);if(f==='ASSOCIACAO_COLUNAS'&&((it.format_payload?.column_i||[]).length!==4||(it.format_payload?.column_ii||[]).length!==4))errors.push(`Q${it.item_number}: associação sem 4x4`);if(f==='DISCURSIVA'&&clean(it.rubric).length<180)errors.push(`Q${it.item_number}: rubrica insuficiente`)}return errors}
export function bpRows(a:any,items:any[]){const bp=a.blueprint?.rows||a.blueprint?.items||[];return items.map((it:any)=>{const r=bp.find((x:any)=>Number(x.item??x.number)===Number(it.item_number))||{};const fam=clean(r.family_dcn??r.family??r.command_family??it.command_family??it.family_dcn??'');const weight=r.weight_percent!=null?`${String(r.weight_percent).replace('.',',')}%`:clean(r.weight||'');return [String(it.item_number),flabel(fmt(it)),clean(it.content_area||r.topic||r.content),clean(it.learning_objective||r.learning_objective||r.objective),clean(it.bloom||r.bloom),clean(r.difficulty||'Médio'),fam,String(words(it.stem)),weight,angoff(a,it)]})}
