export const TEAL='006B63',BLACK='111111',GRAY='666666',LIGHT='EAF5F3';
export const clean=(s:any)=>String(s??'').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/\s+/g,' ').trim();
export const safe=(s:any)=>clean(s).replace(/−/g,'-').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/≠/g,'!=').replace(/→/g,'->').replace(/×/g,'x').replace(/○/g,'( )').replace(/•/g,'-').replace(/✓/g,'V').replace(/µ/g,'u').replace(/³/g,'3').replace(/[^\u0009\u000A\u000D\u0020-\u007E\u00A0-\u00FF]/g,'?');
export const fmt=(x:any)=>String(x.item_format||(x.item_type==='Discursiva'?'DISCURSIVA':'RESPOSTA_UNICA'));
export const flabel=(f:string)=>f==='RESPOSTA_UNICA'?'Resposta única':f==='VERDADEIRO_FALSO'?'V/F':f==='ASSOCIACAO_COLUNAS'?'Associação':'Discursiva';
export const pct=(n:any)=>Number(n||0).toFixed(Number(n||0)%1?1:0).replace('.',',');
export const words=(s:any)=>clean(s).split(/\s+/).filter(Boolean).length;
export const authoredLines=(s:any)=>String(s??'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).length;
export function stemDensityOk(s:any){const n=authoredLines(s),w=words(s);return (n>=7&&n<=10)||(n<=1&&w>=84&&w<=120)}
export function teacher(code:string){return /PASI|PAS1|PAS I/i.test(code)?'Prof. Raimundo Tavares de Luna Neto | Prof. José Evaldo Gomes Júnior':'Prof. Raimundo Tavares de Luna Neto'}
export function canonicalAssessmentType(a:any){return String(a?.assessment_type||a?.type||'').toUpperCase().replace(/\s+/g,'')}
export function canonicalTotal(a:any){const t=canonicalAssessmentType(a);if(t==='AV1')return 9;if(t==='AV2')return 8;return Number(a?.total_points||0)}
export function qValue(a:any,it:any){const t=canonicalAssessmentType(a),n=Number(it?.item_number||0);if(t==='AV1')return n<=8?0.8:1.3;if(t==='AV2')return n<=8?0.7:1.2;const rows=a?.blueprint?.rows||a?.blueprint?.items||[];const r=rows.find((x:any)=>Number(x.item??x.number)===n);const explicit=Number(r?.score_points??r?.points??it?.score_points);if(explicit>0)return explicit;const w=Number(r?.weight_percent||String(r?.weight||'').replace('%','').replace(',','.'));const total=Number(a?.total_points||0),cnt=Number(a?.objective_count||0)+Number(a?.discursive_count||0);return w?total*w/100:total/Math.max(1,cnt)}
export function scoreLabel(a:any,it:any){const v=qValue(a,it);return `Questão ${Number(it.item_number)} - (${pct(v)} ponto${v===1?'':'s'})`}
export function validateScoring(a:any,items:any[]){const errors:string[]=[];const expected=canonicalTotal(a);const sum=items.reduce((s,it)=>s+qValue(a,it),0);if(Math.abs(sum-expected)>.001)errors.push(`canonical_score_sum_mismatch:${sum}:${expected}`);const t=canonicalAssessmentType(a);if(t==='AV1'&&Number(a?.total_points)!==9)errors.push('av1_total_must_be_9');if(t==='AV2'&&Number(a?.total_points)!==8)errors.push('av2_total_must_be_8');for(const it of items){const v=qValue(a,it);if(!(v>0))errors.push(`invalid_item_score:Q${it.item_number}`);if(t==='AV1'){const e=Number(it.item_number)<=8?.8:1.3;if(Math.abs(v-e)>.001)errors.push(`av1_item_score_mismatch:Q${it.item_number}`)}if(t==='AV2'){const e=Number(it.item_number)<=8?.7:1.2;if(Math.abs(v-e)>.001)errors.push(`av2_item_score_mismatch:Q${it.item_number}`)}}return errors}
export function angoff(a:any,it:any){const rows=a.blueprint?.rows||a.blueprint?.items||[];const r=rows.find((x:any)=>Number(x.item??x.number)===Number(it.item_number))||{};const v=r.angoff_modified??r.angoff??r.p_angoff??r.cut_score??it.angoff_modified??it.angoff;return v==null?'A definir':String(v).replace('.',',')}
export function validateAngoff(a:any,items:any[]){const errors:string[]=[];const rows=a?.blueprint?.rows||a?.blueprint?.items||[];const diffs:{label:string,p:number,n:number}[]=[];for(const it of items){const n=Number(it.item_number);const r=rows.find((x:any)=>Number(x.item??x.number)===n)||{};const raw=r.p_angoff??r.angoff_modified??r.angoff;const p=Number(String(raw??'').replace(',','.'));const label=clean(r.dificuldade_estimada??r.difficulty??'');if(!Number.isFinite(p)){errors.push(`angoff_missing:Q${n}`);continue}if(p<.20||p>.95)errors.push(`angoff_out_of_range:Q${n}:${p}`);const l=label.toLowerCase();if(!label)errors.push(`difficulty_missing:Q${n}`);else if(l.startsWith('fácil')||l.startsWith('facil')){if(p<.70||p>.90)errors.push(`angoff_difficulty_mismatch:Q${n}:facil:${p}`)}else if(l.startsWith('médio')||l.startsWith('medio')){if(p<.45||p>.69)errors.push(`angoff_difficulty_mismatch:Q${n}:medio:${p}`)}else if(l.startsWith('difícil')||l.startsWith('dificil')){if(p<.25||p>.44)errors.push(`angoff_difficulty_mismatch:Q${n}:dificil:${p}`)}else errors.push(`difficulty_invalid:Q${n}:${label}`);diffs.push({label:l,p,n})}if(diffs.length===items.length&&items.length>=10){const mean=diffs.reduce((s,x)=>s+x.p,0)/diffs.length;if(mean<.55||mean>.62)errors.push(`angoff_exam_mean_out_of_target:${mean.toFixed(3)}`);const f=diffs.filter(x=>x.label.startsWith('fácil')||x.label.startsWith('facil')).length,m=diffs.filter(x=>x.label.startsWith('médio')||x.label.startsWith('medio')).length,d=diffs.filter(x=>x.label.startsWith('difícil')||x.label.startsWith('dificil')).length;if(f!==2||m!==5||d!==3)errors.push(`angoff_distribution_mismatch:${f}:${m}:${d}:expected_2_5_3`)}return errors}
export function instructions(a:any){return ['Leia cada situação-problema com atenção.','Nas questões objetivas, marque apenas uma alternativa no gabarito.','Nas questões de Verdadeiro/Falso e Associação, assinale a alternativa que representa a sequência correta.','Nas questões discursivas, registre raciocínio, cálculos quando solicitados e interpretação final.',`A prova contém ${a.objective_count} questões objetivas e ${a.discursive_count} discursivas, totalizando ${pct(canonicalTotal(a))} pontos.`]}
export function normalizeOptions(it:any):string[]{return (Array.isArray(it.options)?it.options:[]).map((o:any)=>{if(typeof o==='string')return clean(o);if(o&&typeof o==='object')return clean(o.text??o.label??o.value??o.option??'');return clean(o)}).filter(Boolean)}
export function validateContent(items:any[]){const errors:string[]=[];for(const it of items){const f=fmt(it),opts=normalizeOptions(it),lineCount=authoredLines(it.stem),wordCount=words(it.stem);if(!it.stem||!stemDensityOk(it.stem))errors.push(`Q${it.item_number}: situação-problema fora do padrão 7-10 linhas/84-120 palavras (linhas=${lineCount}, palavras=${wordCount})`);if(f!=='DISCURSIVA'&&opts.length!==5)errors.push(`Q${it.item_number}: deve possuir 5 alternativas`);if(f==='RESPOSTA_UNICA'&&opts.some(x=>x==='[object Object]'||!x))errors.push(`Q${it.item_number}: alternativas corrompidas`);if(f==='VERDADEIRO_FALSO'&&(it.format_payload?.statements||[]).length!==4)errors.push(`Q${it.item_number}: V/F sem 4 sentenças`);if(f==='ASSOCIACAO_COLUNAS'&&((it.format_payload?.column_i||[]).length!==4||(it.format_payload?.column_ii||[]).length!==4))errors.push(`Q${it.item_number}: associação sem 4x4`);if(f==='DISCURSIVA'&&clean(it.rubric).length<180)errors.push(`Q${it.item_number}: rubrica insuficiente`)}return errors}
export function bpRows(a:any,items:any[]){const bp=a.blueprint?.rows||a.blueprint?.items||[];return items.map((it:any)=>{const r=bp.find((x:any)=>Number(x.item??x.number)===Number(it.item_number))||{};const fam=clean(r.family_dcn??r.family??r.command_family??it.command_family??it.family_dcn??'');const value=pct(qValue(a,it))+' pt';return [String(it.item_number),flabel(fmt(it)),clean(it.content_area||r.topic||r.content),clean(it.learning_objective||r.learning_objective||r.objective),clean(it.bloom||r.bloom),clean(r.dificuldade_estimada||r.difficulty||'Médio'),fam,String(words(it.stem)),value,angoff(a,it)]})}
