import {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,ImageRun,Footer,PageNumber,BorderStyle,ShadingType} from 'npm:docx@9.5.1';
import {PDFDocument,StandardFonts,rgb} from 'npm:pdf-lib@1.17.1';
import {headerBytes} from './asset.ts';
import {clean,teacher,canonicalTotal,pct} from './helpers.ts';
const BLACK='111111',TEAL='006B63',LIGHT='EAF5F3';
const run=(t:any,b=false,s=20,c=BLACK)=>new TextRun({text:clean(t),bold:b,font:'Arial',size:s,color:c});
const p=(t:any,b=false,s=20,a=AlignmentType.LEFT)=>new Paragraph({alignment:a,spacing:{after:70},children:[run(t,b,s)]});
const cell=(t:any,h=false)=>new TableCell({shading:h?{type:ShadingType.CLEAR,fill:LIGHT}:undefined,margins:{top:65,bottom:65,left:70,right:70},children:[p(t,h,18,AlignmentType.CENTER)]});
function answerRows(n=10){const rows:any[]=[new TableRow({children:['Q','A','B','C','D','E'].map(x=>cell(x,true))})];for(let i=1;i<=n;i++)rows.push(new TableRow({children:[cell(String(i),true),...['A','B','C','D','E'].map(x=>cell('(   )'))]}));return rows}
export async function makeOmrDocx(a:any,items:any[],c:any,cl:any){const logo=new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:headerBytes(),transformation:{width:640,height:78},type:'png'})]});const id=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[new TableCell({columnSpan:2,children:[p(`FOLHA DE RESPOSTAS — ${a.assessment_type} 2026.2`,true,22,AlignmentType.CENTER)]})]}),new TableRow({children:[cell(`Disciplina: ${c.name}`),cell(`Turma: ${cl?.name||'________'}`)]}),new TableRow({children:[new TableCell({columnSpan:2,children:[p('Aluno(a): _________________________________________________',false,18)]})]}),new TableRow({children:[cell(`Docentes: ${teacher(c.code||c.name)}`),cell(`Valor: ${pct(canonicalTotal(a))} pontos`)]})]});const grid=new Table({width:{size:78,type:WidthType.PERCENTAGE},alignment:AlignmentType.CENTER,borders:{top:{style:BorderStyle.SINGLE,size:5,color:TEAL},bottom:{style:BorderStyle.SINGLE,size:5,color:TEAL},left:{style:BorderStyle.SINGLE,size:5,color:TEAL},right:{style:BorderStyle.SINGLE,size:5,color:TEAL},insideHorizontal:{style:BorderStyle.SINGLE,size:2,color:'AAAAAA'},insideVertical:{style:BorderStyle.SINGLE,size:2,color:'AAAAAA'}},rows:answerRows(Number(a.objective_count||8))});const footer=new Footer({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[run('Estácio–IDOMED – Iguatu | Página ',false,13,'666666'),new TextRun({children:[PageNumber.CURRENT],font:'Arial',size:13,color:'666666'})]})]});const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:20,color:BLACK}}}},sections:[{properties:{page:{margin:{top:360,right:500,bottom:420,left:500}}},footers:{default:footer},children:[logo,id,p('',false,10),p('GABARITO INDIVIDUAL DO ALUNO',true,22,AlignmentType.CENTER),p('Preencha apenas uma alternativa por questão objetiva. Não rasurar os campos de marcação.',false,17,AlignmentType.CENTER),grid,p('',false,12),p('Código/QR individual: __________________________________________',true,17),p('Matrícula/ID: _________________________________________________',false,17),p('Assinatura do aluno: __________________________________________',false,17)]}]});return await Packer.toBuffer(doc)}
function wrap(t:string,n:number){const ws=clean(t).split(/\s+/),o:string[]=[];let l='';for(const w of ws){const x=l?l+' '+w:w;if(x.length>n&&l){o.push(l);l=w}else l=x}if(l)o.push(l);return o}
export async function makeOmrPdf(a:any,items:any[],c:any,cl:any){const pdf=await PDFDocument.create(),page=pdf.addPage([595.28,841.89]),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),logo=await pdf.embedPng(headerBytes()),black=rgb(.05,.05,.05),teal=rgb(0,.42,.39),light=rgb(.92,.97,.96);pdf.setTitle(`${a.title} | OMR_PACKAGE`);pdf.setSubject('IDOMED-CANONICAL-EXAM-V2');const w=523,h=w*(152/1240);page.drawImage(logo,{x:36,y:790-h,width:w,height:h});let y=770-h;const center=(s:string,size=12,b=true)=>{const f=b?bold:font,tw=f.widthOfTextAtSize(s,size);page.drawText(s,{x:(595.28-tw)/2,y,font:f,size,color:black});y-=size+10};center(`FOLHA DE RESPOSTAS — ${a.assessment_type} 2026.2`,12,true);page.drawText(`Disciplina: ${clean(c.name)}`,{x:50,y,font:bold,size:9,color:black});page.drawText(`Turma: ${clean(cl?.name||'________')}`,{x:390,y,font,size:9,color:black});y-=22;page.drawText('Aluno(a): _________________________________________________',{x:50,y,font,size:9,color:black});y-=22;page.drawText(`Docentes: ${clean(teacher(c.code||c.name))}`,{x:50,y,font,size:8.4,color:black});page.drawText(`Valor: ${pct(canonicalTotal(a))} pontos`,{x:430,y,font:bold,size:8.4,color:black});y-=30;center('GABARITO INDIVIDUAL DO ALUNO',11,true);center('Marque somente uma alternativa por questão objetiva.',8,false);const x0=125,rowH=31,colW=58,n=Number(a.objective_count||8);const heads=['Q','A','B','C','D','E'];for(let j=0;j<6;j++){page.drawRectangle({x:x0+j*colW,y:y-rowH,width:colW,height:rowH,color:light,borderColor:teal,borderWidth:.7});page.drawText(heads[j],{x:x0+j*colW+25,y:y-20,font:bold,size:9,color:teal})}y-=rowH;for(let i=1;i<=n;i++){for(let j=0;j<6;j++){page.drawRectangle({x:x0+j*colW,y:y-rowH,width:colW,height:rowH,borderColor:rgb(.65,.65,.65),borderWidth:.45});const text=j===0?String(i):'(     )';page.drawText(text,{x:x0+j*colW+(j===0?26:18),y:y-20,font:j===0?bold:font,size:9,color:black})}y-=rowH}y-=28;for(const s of ['Código/QR individual: __________________________________________','Matrícula/ID: _________________________________________________','Assinatura do aluno: __________________________________________']){page.drawText(s,{x:70,y,font,size:8.5,color:black});y-=22}page.drawLine({start:{x:36,y:28},end:{x:559,y:28},thickness:.7,color:teal});page.drawText(`${clean(c?.code||c?.name||'Medicina')} | Medicina | ${clean(teacher(c?.code||c?.name||''))}`,{x:40,y:14,font,size:6.3,color:black});page.drawText('1',{x:535,y:14,font:bold,size:6.5,color:black});return await pdf.save()}
