import JSZip from 'npm:jszip@3.10.1';
import {PDFDocument} from 'npm:pdf-lib@1.17.1';
import {CANONICAL_HEADER_SHA256,RENDERED_HEADER_SHA256,CANONICAL_TEMPLATE_ID,headerBytes,sourceHeaderBytes} from './asset.ts';
import {fmt,scoreLabel,validateScoring,canonicalTotal} from './helpers.ts';
async function sha(b:Uint8Array){const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const has=(xml:string,s:string)=>xml.includes(s);
export async function validateCanonical(type:string,docx:Uint8Array,pdf:Uint8Array,a?:any,items:any[]=[]){const errors:string[]=[];if(await sha(sourceHeaderBytes())!==CANONICAL_HEADER_SHA256)errors.push('canonical_source_header_hash_mismatch');if(await sha(headerBytes())!==RENDERED_HEADER_SHA256)errors.push('rendered_header_hash_mismatch');const zip=await JSZip.loadAsync(docx);const media=Object.keys(zip.files).filter(k=>/^word\/media\//.test(k));let found=false;for(const k of media){const b=await zip.file(k)?.async('uint8array');if(b&&await sha(b)===RENDERED_HEADER_SHA256)found=true}if(!found)errors.push('official_header_missing_in_docx');const xml=await zip.file('word/document.xml')?.async('string')||'';const headers=(await Promise.all(Object.keys(zip.files).filter(k=>/^word\/header\d+\.xml$/.test(k)).map(k=>zip.file(k)?.async('string')))).filter(Boolean).join('');const footers=(await Promise.all(Object.keys(zip.files).filter(k=>/^word\/footer\d+\.xml$/.test(k)).map(k=>zip.file(k)?.async('string')))).filter(Boolean).join('');if(!has(xml,'Arial')&&!has((await zip.file('word/styles.xml')?.async('string'))||'','Arial'))errors.push('arial_not_declared_docx');if(!has(footers,'IDOMED')&&!has(footers,'Idomed')&&!has(footers,'Estácio'))errors.push('institutional_footer_missing_docx');
if(type==='EXAM_TEMPLATE'){for(const marker of ['GABARITO DO ALUNO','INSTRUÇÕES','Aluno(a):','Turma:','Data:','Valor total:'])if(!has(xml,marker))errors.push('exam_marker_missing:'+marker);if(!headers)errors.push('exam_continuation_header_missing_docx');for(const forbidden of ['Resposta única','Verdadeiro/Falso','Associação de colunas','Discursiva']){const qPattern=new RegExp(`Quest[aã]o\\s+\\d+[^<]{0,60}${forbidden}`,'i');if(qPattern.test(xml))errors.push('item_format_leaked_to_student_exam:'+forbidden)}if(items.length){errors.push(...validateScoring(a,items));for(const it of items){const marker=scoreLabel(a,it);if(!has(xml,marker))errors.push(`item_score_missing:Q${it.item_number}`)}if(items.some(x=>fmt(x)==='ASSOCIACAO_COLUNAS')&&!has(xml,'COLUNA I'))errors.push('association_columns_missing_docx');if(items.some(x=>fmt(x)==='VERDADEIRO_FALSO')&&!has(xml,'Assinale a alternativa que apresenta a sequência correta.'))errors.push('vf_instruction_missing_docx')}if(!has(xml,`totalizando ${String(canonicalTotal(a)).replace('.',',')}`)&&!has(xml,`totalizando ${canonicalTotal(a)}`))errors.push('canonical_total_missing_in_instructions')}
if(type==='OMR_PACKAGE'){for(const marker of ['FOLHA DE RESPOSTAS','GABARITO INDIVIDUAL DO ALUNO','Aluno(a):','Matrícula/ID:','Código/QR individual:','A','B','C','D','E'])if(!has(xml,marker))errors.push('omr_marker_missing:'+marker);if(!has(xml,`${String(canonicalTotal(a)).replace('.',',')} pontos`)&&!has(xml,`${canonicalTotal(a)} pontos`))errors.push('omr_canonical_total_missing')}
if(type==='BLUEPRINT_REPORT'){for(const marker of ['RELATÓRIO DO BLUEPRINT','Angoff','Bloom','Peso','Formato'])if(!has(xml,marker))errors.push('blueprint_marker_missing:'+marker)}if(type==='COMMENTED_KEY'&&!has(xml,'GABARITO COMENTADO'))errors.push('commented_key_title_missing_docx');if(type==='TECHNICAL_DOSSIER'){for(const marker of ['CADERNO TÉCNICO DO PROFESSOR','Angoff','APROVADO PARA APLICAÇÃO DOCENTE'])if(!has(xml,marker))errors.push('dossier_marker_missing:'+marker)}const p=await PDFDocument.load(pdf);if(p.getSubject()!==CANONICAL_TEMPLATE_ID)errors.push('canonical_pdf_marker_missing');const pages=p.getPages();if(!pages.length)errors.push('pdf_without_pages');if(type==='EXAM_TEMPLATE'&&items.length){const expected=1+Math.ceil(items.filter(x=>fmt(x)!=='DISCURSIVA').length/4)+items.filter(x=>fmt(x)==='DISCURSIVA').length;if(pages.length!==expected)errors.push(`exam_page_count_mismatch:${pages.length}:${expected}`)}if(type==='OMR_PACKAGE'&&pages.length!==1)errors.push('omr_must_be_single_page');if(type==='BLUEPRINT_REPORT'&&pages[0]&&pages[0].getWidth()<=pages[0].getHeight())errors.push('blueprint_not_landscape');for(const [i,page] of pages.entries()){const {width,height}=page.getSize();if(width<500||height<500)errors.push(`invalid_page_geometry:${i+1}`)}return {passed:errors.length===0,errors,template_id:CANONICAL_TEMPLATE_ID,header_sha256:CANONICAL_HEADER_SHA256,rendered_header_sha256:RENDERED_HEADER_SHA256,page_count:pages.length}}
